### ISSUE TITLE
search shouldn't be blocked when indexing

### ISSUE THREAD

**Issue by nbittich** [mu-semtech/mu-search#42]
The search feature shouldn't be blocked when indexing. This happens when a user with a group that is not  known by mu-search (through eager indexing config) triggers the indexing by searching over data where no index were created yet.

It blocks the searching for everyone, including the indexes that are already ok.

**Comment by nvdk** [comment]
FYI I couldn't reproduce this

**Comment by cecemel** [comment]
@nvdk I think with the giga cluster we have i could reproduce it.
Basically, update comes in, mu-search is looking very hard what index to update and meanwhile logging in blocks.

**Comment by nvdk** [comment]
It would be great if you could check with both the `semtech/mu-search:0.8.0` and `semtech/mu-search:feature-inheritance-and-composite-types` builds. both have some improvements to delta handling that might mitigate this.

**Comment by nvdk** [comment]
ping: can @cecemel or @nbittich confirm this can be closed?

**Comment by nbittich** [comment]
@nvdk we just migrate to mu-search 0.9.0 beta in OP. it is deployed in development but not yet in QA. Once deployed in QA I will let you know if that has been fixed (since we need to have to reindex QA, I will be able to check it )
