### ISSUE TITLE
number_of_threads should be an environment variable

### ISSUE THREAD

**Issue by nbittich** [mu-semtech/mu-search#45]
number_of_threads is something that we can update depending on the machine, while properties and types to index are common.
I think it would be better to remove it from config.json and have it as an environment variable, so we can update it in docker-compose.override without having to revert it before commit it on github;

**Comment by erikap** [comment]
This should already be possible @nbittich . See [the configuration options section in the README](https://github.com/mu-semtech/mu-search#configuration-options)

> All options prefixed with (*) can also be configured using an UPPERCASED variant as Docker environment variables on the mu-search container. E.g. the batch_size option can be set via the environment variable BATCH_SIZE. Environment variables take precedence over settings configured in config.json.

**Comment by nbittich** [comment]
Ah I missed that line: `All options prefixed with (*) can also be configured using an UPPERCASED variant as Docker environment variables on the mu-search container. `

thank you!
