### ISSUE TITLE
offer an option to eager index by using direct virtuoso endpoint

### ISSUE THREAD

**Issue by nbittich** [mu-semtech/mu-search#72]
The eager indexing can take hours to be achieved.
On my machine, a batch is processed in  20-30 seconds with mu auth.
By changing the link of the database to direct virtuoso endpoint on my docker compose file, now the batch are processed in 5-7 seconds.
I don't think mu auth is needed for the eager indexing step, so we could maybe have an option to override the sparql endpoint for the eager indexing only

**Comment by nvdk** [comment]
I'm afraid we do need mu-auth to correctly select data based on the user groups, so this is not an option.
